### ISSUE TITLE
NAN

### ISSUE THREAD

**Issue by sweetquiet** [asl-beachbot/localization#2]
Hi! I tried run it , but I find [NAN](https://github.com/asl-beachbot/localization/blob/8b892692cdca2d6c9303f280f37077c649e6309f/src/find_poles.cpp#L123), How can I do it ? thank you verry much!

**Comment by wolfv** [comment]
hey @sweetquiet , this code was written when we were pretty young students. Not sure if it's something that should be re-used as-is :) but feel free to take some inspiration from it.

**Comment by sweetquiet** [comment]
Hey@wolfv Thanks for your reply, I did get inspired in this code, thank you again！
